# Generated by Django 5.2.4 on 2026-04-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='competed',
            new_name='completed',
        ),
    ]
