# Form implementation generated from reading ui file 'thecalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 585)
        Form.setStyleSheet("QFrame{\n"
"background-color:#000000;\n"
"\n"
"}\n"
"QLabel{\n"
"font-size:25px;\n"
"font-family:\"Helvetica\";\n"
"color:\"#fff\";\n"
"\n"
"}\n"
"#close_btn{\n"
"background-color:#000;\n"
"\n"
"}\n"
"#function_frame{\n"
"border-bottom:1px solid #333333;\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"}\n"
"#buttons_frame{\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"}\n"
"#buttons_frame QLineEdit{\n"
"background-color:#000000;\n"
"color:#FFF;\n"
"border:none;\n"
"height:100px;\n"
"padding:10px 5px;\n"
"font-size:100px;\n"
"font-family:\"Segeo UI\";\n"
"}\n"
"#buttons_frame QPushButton {\n"
"    background-color:#555;   /* final color */\n"
"    color:#FFF;\n"
"    font-size:30px;\n"
"    font-family:\"Helvetica\";\n"
"    border-radius: 25px;     /* half of width/height */\n"
"    min-width:50px;\n"
"    min-height:50px;\n"
"\n"
"}\n"
"#buttons_frame QPushButton:pressed {\n"
"    background-color: #555;\n"
"}\n"
"#buttons_frame #zero_btn{\n"
"font-size:40px;}\n"
"#buttons_frame QPushButton[class=\"btn_group1\"] {\n"
"    background: #a5a5a5;\n"
"    color:#020202;\n"
"    font-size:45px;\n"
"}\n"
"\n"
"#buttons_frame QPushButton[class=\"btn_group1\"]:pressed {\n"
"    background:#d6d6d6;   /* fixed typo */\n"
"}\n"
"#buttons_frame QPushButton[class=\"btn_group2\"] {\n"
"    background: #ca3401;\n"
"font-size:30px;\n"
"}\n"
"#buttons_frame QPushButton[class=\"btn_group2\"]:checked,\n"
"#buttons_frame QPushButton[class=\"btn_group2\"]:pressed {\n"
"    background: #fff;\n"
"color:#ca3401;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.function_frame = QtWidgets.QFrame(parent=Form)
        self.function_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.function_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.function_frame.setObjectName("function_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.function_frame)
        self.horizontalLayout.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.function_frame)
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("calculator.bmp"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.function_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(555, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_Btn = QtWidgets.QPushButton(parent=self.function_frame)
        self.close_Btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cancel.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_Btn.setIcon(icon)
        self.close_Btn.setIconSize(QtCore.QSize(30, 30))
        self.close_Btn.setObjectName("close_Btn")
        self.horizontalLayout.addWidget(self.close_Btn)
        self.gridLayout_2.addWidget(self.function_frame, 0, 0, 1, 1)
        self.buttons_frame = QtWidgets.QFrame(parent=Form)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.buttons_frame)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 4, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 3, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 3, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 3, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 4, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 4, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 5, 2, 1, 1)
        self.zero_btn = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.zero_btn.setObjectName("zero_btn")
        self.gridLayout.addWidget(self.zero_btn, 5, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 5, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.buttons_frame)
        self.pushButton_15.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("maths.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon1)
        self.pushButton_15.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.buttons_frame)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 4)
        self.gridLayout_2.addWidget(self.buttons_frame, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Calculator"))
        self.pushButton_3.setText(_translate("Form", "CE"))
        self.pushButton_3.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_2.setText(_translate("Form", "%"))
        self.pushButton_2.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_5.setText(_translate("Form", "Omit"))
        self.pushButton_5.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_4.setText(_translate("Form", "C"))
        self.pushButton_4.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_6.setText(_translate("Form", "+"))
        self.pushButton_6.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_9.setText(_translate("Form", "8"))
        self.pushButton_19.setText(_translate("Form", "4"))
        self.pushButton_8.setText(_translate("Form", "9"))
        self.pushButton_13.setText(_translate("Form", "1"))
        self.pushButton_20.setText(_translate("Form", "6"))
        self.pushButton_21.setText(_translate("Form", "5"))
        self.pushButton_18.setText(_translate("Form", "-"))
        self.pushButton_18.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_11.setText(_translate("Form", "2"))
        self.pushButton_12.setText(_translate("Form", "3"))
        self.pushButton_10.setText(_translate("Form", "/"))
        self.pushButton_10.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_16.setText(_translate("Form", "="))
        self.zero_btn.setText(_translate("Form", "0"))
        self.pushButton_14.setText(_translate("Form", "*"))
        self.pushButton_14.setProperty("class", _translate("Form", "btn_group2"))
        self.lineEdit.setText(_translate("Form", "0"))
